= Deploying to production
:toc: right
:imagesdir: media/

In this chapter you will launch cloud instances of both Enonic and Next - link them together, and watch the glorious result.

== Introduction
Running a full production setup involves running a single instance of Enonic XP, and two instances of the Next.js application - one for preview, and one for handling the live traffic. For simplicity, let's use Enonic, and Vercel to host the respective apps - Vercel are the makers of Next.js. 

NOTE: Enonic and Next.js are both open source software projects and can be deployed more or less anywhere. Have a look at the https://developer.enonic.com/docs/kubernetes-operator-for-xp[Kubernetes operator for Enonic XP] if you are keen on hosting it yourself.

== Task: Sign up to Enonic and deploy your app

Follow the steps below to deploy your app on Enonic Cloud:

. **Sign up** for a https://enonic.com/sign-up/cloud-trial[free trial] and create your personal account.
. **Create a new solution** (NOTE: Choose the `CMS essentials` template), and go with the default values
. **Connect Enonic CLI to the cloud** by running this command, and follow the instructions:
+
[source,bash,{subs}]
----
enonic cloud login
----
+ 
. From your Enonic app folder, install the app by running this command:
+
[source,bash,{subs}]
----
enonic cloud app install
----
+ 
. Going back to the Enonic cloud solution, verify that the app was installed to your selected environment.
+
TODO Screenshot
+
. Finally, log into your Enonic XP cloud instance and launch Content Studio to verify that the app automatically initialized the `hmdb` site on the server, just like on your local machine.
+
NOTE: You may optionally delete the standard content, export and import your local machine content using the https://market.enonic.com/vendors/glenn-ricaud/data-toolbox[Data Toolbox application].


== Task: Expose drafts API via route

In order for the Next app to access the draft items and API, you will need to create a so-called route in the Enonic Cloud.

TIP: The purpose of routes is to expose internal endpoints like `:8080/site/<project>/<branch>/<path-to-site>` to the internet.

. Via the Cloud Solution interface, go to `Routes` and create a new route called "HMDB Drafts".
+
Use the following settings:
TODO:
+
. After the route has started, click the URL in route details to verify that it is working - you should be getting a "403 error" page. (NOTE: To access the API, append `/_graphql` to the end of this URL).

== Task: Sign up and deploy the preview app to Vercel

With the drafts API online, you are ready to launch the Next preview server.

. Sign up to Vercel
. Configure with route to Enonic
TODO

== Task: Link Enonic to the preview server

At this moment, Content Studio is still not able to access the preview server, as you might remember it uses http://localhost:3000 as it's default location.

. From the Enonic Cloud interface, choose `Applications`, select and `Edit` the your app from the details panel.
. Paste the following into the configuration field: `nextjsurl=<full url to next preview server>` - i.e. nextjsurl=myapp.vercel.com 
. Save the changes, and wait for the configuration to be applied
. The preview should now be working in Content Studio - yay!.


== Task: Go live

Finally, it's time to go live. Follow these steps to get there:

. **Publish your site** and content. In Content Studio, selecting the site, then press `Publish Tree` from the right action menu dropdown.
. **Create the "HMDB" route** from the Enonic Cloud interface, this time, use the following configuration values: TODO
. **Create a new project and deploy the production app to Vercel**, the process is essentially the same as for the preview app - but this time we will configure it to use the URL to the new `HMDB` route.
. Verify that your site is now live

== Summary, and whats next?

You've reached the end of this tutorial - we hope you enjoyed it!

The following topics were not covered, but will be added in later revisions of this tutorial:

* Securing your drafts API and preview server
* Importing and exporting content between instances
* TODO

There are obviously many aspects of Enonic and Next.js that will never be covered by this tutorial, however - you should check out the following links to learn even more:

TODO
* Developer 101
* Developer portal
* Vercel: https://nextjs.org/learn/basics/deploying-nextjs-app/github
