= Page templates
:toc: right
:imagesdir: media/
:sourcedir: ../src

Thus far, page rendering has been based on hard-coding by developers, or editorially composing single pages. In this chapter you'll learn how to make page templates - and reuse them across multiple content items.

## Task: Movie details part

To complete this section, we'll need one more part for listing movie details. The content type and content for movies already exists in Enonic, so lets get to work.

. **Add the `movie-details` part to Enonic** - same procedure as earlier...
+
.src/main/resources/site/parts/movie-details/movie-details.xml
[source,xml]
----
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<part xmlns="urn:enonic:xp:model:1.0">
    <display-name>Movie Details</display-name>
    <description>Show details of a movie</description>
    <form/>
</part>
----
+
.src/main/resources/site/parts/movie-details/movie-details.js
[source,JavaScript]
----
var proxy = require('/lib/nextjs-proxy/proxy');

exports.get = proxy.get;
----
+
. **Redeploy** the Enonic app and add the part to your page
+
. **Register the Movie query and view** in Next.
+
[source,JavaScript]
----
include::{sourcedir}/components/parts/MovieDetails.tsx[]
----
Add the following lines to _mappings.ts:
+
.src/components/_mappings.ts
[source,javascript,options="nowrap"]
----
import MovieDetails, {getMovie} from './parts/MovieDetails';

...

ComponentRegistry.addPart(`${APP_NAME}:movie-details`, {
    query: getMovie,
    view: MovieDetails
});

----

== Task: Create template

With the new component registered, its time to put it to use.

. In Content Studio, select and **edit your favorite movie** (or choose "No time to die" if you have no faviorites).
+
. Like before, activate the page editor, select the "main" page component and **add the "Movie details" part** to the page.
+
TODO: Screenshot
+
We now have a single movie nicely presented, but it would be cumbersome to manually configure each movie like this - page templates to the rescue.
+
. In the page editor, **select the page component** (for instance by clicking on the header).
+
. Click **Save as template** from the right hand panel that appears.
+
This will create a new page template content item, and open it in a new tab for editing.
+
. **Give your template a better name**, such as "Movie details" and save the changes.
+
. Try visiting other movie items to **verify they now automatically render**.

With templates sorted out, the development is more or less complete - <<deployment#, and the apps are ready for prime time>>.